### ISSUE TITLE
Overriding inlining of rdf:type

### ISSUE THREAD

**Issue by johanwk** [VladimirAlexiev/rdf2rml#14]
I have an ontology with both classes and individuals. It would be good to _not_ inline some cases of rdf:type, to emphasise how various individuals belong to different parts of the class taxonomy.

Is there a way to request the opposite of `puml:InlineProperty`? Preferably, this would be applied only to selected rdf:type triples (the default format with inlining of rdf:type helps a lot to avoid busy diagrams).

**Comment by VladimirAlexiev** [comment]
@johanwk Give me an example, because I think this works now:

- https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/unicode is a delightful example about icecream.
Notice how the instance `(I)` (bottom right) refers to a class that's inlined in the instance,
but is also shown as `(C)` node (top left)
- https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/blank-types shows classes defined with restrictions
- https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/vlaanderen shows lots of classes (it's an ugly example)

**Comment by johanwk** [comment]
Please take a look at the following example? It uses regular arrows marked with "a" for rdf:type.

[ex-artefact-make-ttl.pdf](https://github.com/VladimirAlexiev/rdf2rml/files/14808534/ex-artefact-make-ttl.pdf)

**Comment by VladimirAlexiev** [comment]
@johanwk Got it. Please show the source so I can use it as an example.
- https://github.com/VladimirAlexiev/rdf2rml/blob/master/doc/rdfpuml.md#reification shows an option `puml:NoReify`. I'll make a similar option `puml:NoInline`
- It will work on individual nodes (in your case classes).
- But do you also need it to work on groups of nodes? (eg `puml:InlineProperty` says "inline all values of that prop")

**Comment by VladimirAlexiev** [comment]
https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/blank-types#readme
